name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%m%d%H')" >> $GITHUB_ENV

      - name: Echo current date
        run: echo $NOW

      - name: checkout source code
        uses: actions/checkout@master

      - name: npm install(client)
        working-directory: ./client
        run: npm install

      - name: react build
        working-directory: ./client
        run: CI=false npm run build

      - name: node.js build
        working-directory: ./server
        run: npm run build

      - name: docker build
        run: docker build -t junehay/chartgame:0.$NOW .

      - name: docker login
        run: docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PWD}}

      - name: docker-hub push
        run: docker push ${{secrets.DOCKER_NAME}}/chartgame:0.$NOW

      - name: docker latest tag
        run: docker tag ${{secrets.DOCKER_NAME}}/chartgame:0.$NOW ${{secrets.DOCKER_NAME}}/chartgame:latest

      - name: docker-hub push(latest)
        run: docker push ${{secrets.DOCKER_NAME}}/chartgame:latest
