name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@master
    
      - name: node_modules delete
        working-directory: ./client
        run: rm -rf node_modules package-lock.json
        
      - name: npm install
        working-directory: ./client
        run: npm install
        
      - name: react build
        working-directory: ./client
        run: CI=false npm run build

      - name: docker build
        run: docker build -t junehay/chartgame:v1.1005 .
          
      - name: docker login
        run: docker login -u ${{secrets.DOCKER_NAME}} -p ${{secrets.DOCKER_PWD}}
      
      - name: docker-hub push
        run: docker push ${{secrets.DOCKER_NAME}}/chartgame:v1.1005
